from __future__ import annotations

import unittest

from ida_pseudoforge.core.plan_schema import (
    CleanPlan,
    CleanupLabel,
    FlowRewrite,
    FunctionCapture,
    FunctionIdentityCandidate,
    ParameterTypeCorrection,
    RenameSuggestion,
)
from ida_pseudoforge.core.render_header import (
    MAX_KERNEL_INSIGHT_COMMENTS,
    kernel_semantic_rewrite_count,
    render_header_lines,
)


def _plan() -> CleanPlan:
    plan = CleanPlan(
        function_ea=0x140001000,
        function_name="Sample",
        input_fingerprint="fp",
    )
    plan.renames.append(RenameSuggestion("lvar", "a1", "argument0", 0.82, "prototype", "fixture"))
    plan.flow_rewrites.append(FlowRewrite(kind="switch", dispatcher="code", recovered_cases=[1, 2], confidence=0.91))
    plan.comments.append({"kind": "critical_region", "text": "한글 insight", "confidence": 0.9})
    plan.cleanup_labels.append(
        CleanupLabel(
            label="LABEL_1",
            classification="release_resource_and_leave_critical_region",
            start_line=10,
            end_line=12,
            confidence=0.88,
            evidence="cleanup tail",
        )
    )
    return plan


class RenderHeaderTests(unittest.TestCase):
    def test_render_header_lines_includes_flow_comments_labels_warnings_and_renames(self) -> None:
        plan = _plan()
        capture = FunctionCapture(ea=0x140001000, name="Sample", pseudocode="")

        header = "\n".join(
            render_header_lines(
                capture,
                plan,
                {"a1": "argument0"},
                ["manual warning"],
                {"code"},
                "0.1.0",
            )
        )

        self.assertIn("Generated by PseudoForge.", header)
        self.assertIn("Kernel semantic rewrites: 2", header)
        self.assertIn("Flow: switch dispatcher=code cases=[1, 2] confidence=0.91 source=native_switch", header)
        self.assertIn("\\ud55c\\uae00 insight", header)
        self.assertIn("Label roles:", header)
        self.assertIn("Warning detail:", header)
        self.assertIn("Renames: a1->argument0(0.82,prototype)", header)

    def test_kernel_semantic_rewrite_count_counts_known_comments_and_labels(self) -> None:
        self.assertEqual(kernel_semantic_rewrite_count(_plan()), 2)

    def test_render_header_keeps_twenty_kernel_insights(self) -> None:
        plan = CleanPlan(
            function_ea=0x140001000,
            function_name="Sample",
            input_fingerprint="fp",
        )
        for index in range(MAX_KERNEL_INSIGHT_COMMENTS + 1):
            plan.comments.append(
                {
                    "kind": "test_comment_%d" % index,
                    "text": "comment %d" % index,
                    "confidence": 0.5,
                }
            )
        capture = FunctionCapture(ea=0x140001000, name="Sample", pseudocode="")

        header = "\n".join(
            render_header_lines(
                capture,
                plan,
                {},
                [],
                set(),
                "0.1.0",
            )
        )

        self.assertIn("test_comment_19", header)
        self.assertNotIn("test_comment_20", header)

    def test_render_header_preserves_critical_layout_rewrite_comments_after_limit(self) -> None:
        plan = CleanPlan(
            function_ea=0x140001000,
            function_name="Sample",
            input_fingerprint="fp",
        )
        for index in range(MAX_KERNEL_INSIGHT_COMMENTS + 3):
            plan.comments.append(
                {
                    "kind": "test_comment_%d" % index,
                    "text": "comment %d" % index,
                    "confidence": 0.5,
                }
            )
        plan.comments.append(
            {
                "kind": "inferred_offset_rewrite_ready",
                "text": (
                    "Offset field rewrite candidate for context: 12 typed dereference(s) across "
                    "8 offset(s), no rewrite blockers found. Audit only; body rewrite was not applied."
                ),
                "confidence": 0.8,
            }
        )
        plan.comments.append(
            {
                "kind": "inferred_offset_rewrite_preview",
                "text": (
                    "Offset field rewrite preview for context: 12 dereference(s) can map to "
                    "8 field alias(es) field_10, field_18. Preview artifact only; body rewrite was not applied."
                ),
                "confidence": 0.78,
            }
        )
        capture = FunctionCapture(ea=0x140001000, name="Sample", pseudocode="")

        header = "\n".join(
            render_header_lines(
                capture,
                plan,
                {},
                [],
                set(),
                "0.1.0",
            )
        )

        self.assertIn("test_comment_19", header)
        self.assertNotIn("test_comment_20", header)
        self.assertIn("inferred_offset_rewrite_ready", header)
        self.assertIn("inferred_offset_rewrite_preview", header)

    def test_render_header_preserves_bitfield_alias_comments_after_limit(self) -> None:
        plan = CleanPlan(
            function_ea=0x140001000,
            function_name="Sample",
            input_fingerprint="fp",
        )
        for index in range(MAX_KERNEL_INSIGHT_COMMENTS + 3):
            plan.comments.append(
                {
                    "kind": "test_comment_%d" % index,
                    "text": "comment %d" % index,
                    "confidence": 0.5,
                }
            )
        plan.comments.append(
            {
                "kind": "inferred_offset_bitfield_aliases",
                "text": (
                    "Bitfield aliases for parseContext: InternalFlags=+0x98 "
                    "bitfield_single_bit masks=0x8."
                ),
                "confidence": 0.74,
            }
        )
        capture = FunctionCapture(ea=0x140001000, name="Sample", pseudocode="")

        header = "\n".join(
            render_header_lines(
                capture,
                plan,
                {},
                [],
                set(),
                "0.1.0",
            )
        )

        self.assertIn("test_comment_19", header)
        self.assertNotIn("test_comment_20", header)
        self.assertIn("inferred_offset_bitfield_aliases", header)
        self.assertIn("InternalFlags=+0x98", header)

    def test_render_header_sanitizes_generated_comment_prose(self) -> None:
        plan = CleanPlan(
            function_ea=0x140001000,
            function_name="Sample",
            input_fingerprint="fp",
        )
        plan.comments.append(
            {
                "kind": "domain_structure_identity",
                "text": "field evidence mixed(_KPROCESS */_QWORD)\r\nraw /* marker",
                "confidence": 0.82,
                "profile_id": "profile mixed(_KPROCESS */_QWORD)",
                "structure": "EPROCESS",
                "blockers": ["blocker /* raw"],
            }
        )
        plan.cleanup_labels.append(
            CleanupLabel(
                label="LABEL_1",
                classification="release_resource_and_leave_critical_region",
                start_line=4,
                end_line=6,
                confidence=0.91,
                evidence="label evidence mixed(_DWORD */_QWORD)\nnext /* marker",
            )
        )
        plan.function_identity_candidates.append(
            FunctionIdentityCandidate(
                profile_id="function profile mixed(_DWORD */_QWORD)",
                subsystem="kernel",
                function_name="Sample",
                match_kind="body_identity",
                confidence=0.77,
                blockers=["identity /* blocker"],
                effective_mode="report-only",
            )
        )
        plan.type_corrections.append(
            ParameterTypeCorrection(
                parameter_index=0,
                old_name="a1",
                new_name="process",
                old_type="mixed(_KPROCESS */_QWORD)",
                canonical_type="_KPROCESS *",
                profile_id="type profile /* raw",
                display_type="mixed(_DWORD */_QWORD)",
                blockers=["type blocker /* raw"],
                apply_to_preview=False,
            )
        )
        capture = FunctionCapture(ea=0x140001000, name="Sample*/Name", pseudocode="")

        lines = render_header_lines(
            capture,
            plan,
            {},
            [{"message": "warning mixed(_DWORD */_QWORD)\r\nnext /* marker"}],
            set(),
            "0.1.0",
        )
        generated_lines = lines[1:-1]
        header = "\n".join(lines)
        generated_text = "\n".join(generated_lines)

        self.assertEqual("/*", lines[0])
        self.assertEqual("*/", lines[-1])
        self.assertTrue(all("\r" not in line and "\n" not in line for line in lines))
        self.assertNotIn("*/", generated_text)
        self.assertNotIn("/*", generated_text)
        self.assertIn("mixed(_KPROCESS * /_QWORD)", header)
        self.assertIn("mixed(_DWORD * /_QWORD)", header)
        self.assertIn("raw / * marker", header)
        self.assertIn("\\nnext", header)


if __name__ == "__main__":
    unittest.main()
