import unittest

from ida_pseudoforge.core.capture import capture_from_pseudocode
from ida_pseudoforge.core.normalize import (
    extract_calls,
    extract_function_name,
    extract_function_signature,
)


class NormalizeTests(unittest.TestCase):
    def test_extract_function_signature_skips_pseudoforge_block_headers(self) -> None:
        text = """
/*
    Generated by PseudoForge.
    Function: KiWakeQueueWaiter
    Kernel insights:
      - failfast: FAST_FAIL_CORRUPT_LIST_ENTRY style path detected
    Label roles:
      - LABEL_5 -> CorruptListEntry: failfast_corrupt_list_entry confidence=0.96 (Calls __fastfail(3), commonly emitted for corrupt LIST_ENTRY integrity checks)
*/

/*
    PseudoForge normalized original pseudocode.
*/

char __fastcall KiWakeQueueWaiter(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return a1 != 0 && a2 != 0;
}
"""

        signature = extract_function_signature(text)
        calls = extract_calls(text)
        capture = capture_from_pseudocode(text)

        self.assertEqual(
            "char __fastcall KiWakeQueueWaiter(__int64 a1, __int64 a2, __int64 a3, __int64 a4)",
            signature,
        )
        self.assertEqual("KiWakeQueueWaiter", extract_function_name(signature))
        self.assertEqual("KiWakeQueueWaiter", capture.name)
        self.assertNotIn("__fastfail", calls)


if __name__ == "__main__":
    unittest.main()
