from __future__ import annotations

from collections import Counter

from ida_pseudoforge.core.plan_schema import CleanPlan, FunctionCapture
from ida_pseudoforge.core.domain_identity_summary import format_domain_identity_summary
from ida_pseudoforge.core.render_flow import format_flow_case_value
from ida_pseudoforge.core.render_labels import (
    semantic_label_display,
    semantic_label_map,
    semantic_label_name,
)
from ida_pseudoforge.core.render_status import _has_status_accumulator
from ida_pseudoforge.core.render_warnings import format_warning


MAX_KERNEL_INSIGHT_COMMENTS = 20
CRITICAL_KERNEL_INSIGHT_KINDS = {
    "dense_accumulator_block",
    "dense_stack_local_region",
    "inferred_offset_bitfield_aliases",
    "inferred_offset_rewrite_partial_opportunity",
    "inferred_offset_rewrite_preview",
    "inferred_offset_rewrite_ready",
    "review_only_struct_candidate",
}


def render_header_lines(
    capture: FunctionCapture,
    plan: CleanPlan,
    rename_map: dict[str, str],
    display_warnings: list[object],
    native_switch_dispatchers: set[str],
    version: str,
) -> list[str]:
    header = [
        "/*",
        "    Generated by PseudoForge.",
        f"    Version: {version}",
        "    Preview/export only. IDB was not modified.",
        f"    Function: {capture.name}",
        f"    Fingerprint: {plan.input_fingerprint}",
        f"    Rename candidates: {len(rename_map)}",
        f"    Flow rewrites: {len(plan.flow_rewrites)}",
        f"    Kernel semantic rewrites: {kernel_semantic_rewrite_count(plan)}",
        f"    Warnings: {len(display_warnings)}",
    ]

    if plan.flow_rewrites:
        for flow in plan.flow_rewrites:
            cases = ", ".join(format_flow_case_value(flow, value) for value in flow.recovered_cases[:64])
            if len(flow.recovered_cases) > 64:
                cases += ", ..."
            source_suffix = ""
            if flow.dispatcher in native_switch_dispatchers:
                source_suffix = " source=native_switch outline=suppressed"
            header.append(
                f"    Flow: {flow.kind} dispatcher={flow.dispatcher} cases=[{cases}] "
                f"confidence={flow.confidence:.2f}{source_suffix}"
            )

    domain_summary = format_domain_identity_summary(plan)
    if domain_summary:
        for line in domain_summary.splitlines():
            header.append(f"    {line}")

    function_identity_summary = format_function_identity_candidate_summary(plan)
    if function_identity_summary:
        for line in function_identity_summary.splitlines():
            header.append(f"    {line}")

    type_summary = format_parameter_type_correction_summary(plan)
    if type_summary:
        for line in type_summary:
            header.append(f"    {line}")

    if plan.comments:
        header.append("    Kernel insights:")
        for comment in _kernel_insight_comments(plan):
            kind = _ascii_comment_text(str(comment.get("kind", "kernel")))
            confidence = float(comment.get("confidence", 0.0))
            text_value = _ascii_comment_text(str(comment.get("text", "")))
            header.append(f"      - {kind}: {text_value} confidence={confidence:.2f}")

    if plan.cleanup_labels:
        header.append("    Label roles:")
        labels = semantic_label_map(plan)
        for label in plan.cleanup_labels[:16]:
            display_label = semantic_label_display(label.label, label.classification, labels)
            evidence = _ascii_comment_text(label.evidence)
            header.append(
                f"      - {display_label}: {label.classification} confidence={label.confidence:.2f} "
                f"({evidence})"
            )

    if display_warnings:
        header.append("    Warning detail:")
        for warning in display_warnings[:8]:
            header.append(f"      - {format_warning(warning)}")
        if len(display_warnings) > 8:
            header.append(f"      - ... {len(display_warnings) - 8} more warning(s)")

    if rename_map:
        rename_items = {
            item.old: item
            for item in plan.renames
            if item.apply and rename_map.get(item.old) == item.new
        }
        pairs = ", ".join(
            f"{old}->{item.new}({item.confidence:.2f},{item.source})"
            for old, item in sorted(rename_items.items())
        )
        if pairs:
            header.append(f"    Renames: {pairs}")

    header.append("*/")
    return header


def _kernel_insight_comments(plan: CleanPlan) -> list[dict[str, object]]:
    selected = list(plan.comments[:MAX_KERNEL_INSIGHT_COMMENTS])
    selected_ids = {id(comment) for comment in selected}
    for comment in plan.comments[MAX_KERNEL_INSIGHT_COMMENTS:]:
        if id(comment) in selected_ids:
            continue
        if str(comment.get("kind", "")) not in CRITICAL_KERNEL_INSIGHT_KINDS:
            continue
        selected.append(comment)
        selected_ids.add(id(comment))
    return selected


def kernel_semantic_rewrite_count(plan: CleanPlan) -> int:
    count = 0
    rewrite_comment_kinds = {
        "callback_registration",
        "critical_region",
        "device_extension_layout",
        "driver_dispatch_table",
        "driver_entry",
        "inferred_record_layout",
        "list_entry_insert_tail",
        "list_entry_unlink",
        "memory_manager_probe",
        "pool_tag",
        "registry_callback_registration",
        "zw_api_probe",
    }
    for comment in plan.comments:
        if str(comment.get("kind", "")) in rewrite_comment_kinds:
            count += 1
    count += len([label for label in plan.cleanup_labels if semantic_label_name(label.classification)])
    if _has_status_accumulator(plan):
        count += 1
    return count


def format_function_identity_candidate_summary(plan: CleanPlan, top_limit: int = 5) -> str:
    candidates = list(plan.function_identity_candidates)
    if not candidates:
        return ""
    mode_counts: Counter[str] = Counter(str(item.effective_mode or "") for item in candidates)
    blocker_counts: Counter[str] = Counter()
    profile_counts: Counter[str] = Counter()
    for item in candidates:
        if item.profile_id:
            if item.profile_id == "ambiguous":
                for profile_id in item.ambiguous_profile_ids:
                    if profile_id:
                        profile_counts[str(profile_id)] += 1
            else:
                profile_counts[str(item.profile_id)] += 1
        for blocker in item.blockers:
            if blocker:
                blocker_counts[str(blocker)] += 1
    lines = [
        (
            "Function identities: %d candidate(s), %d report-only, %d preview-rewrite, "
            "%d canonical-rewrite-eligible."
        )
        % (
            len(candidates),
            mode_counts["report-only"],
            mode_counts["preview-rewrite"],
            mode_counts["canonical-rewrite-eligible"],
        )
    ]
    top_profiles = [
        profile_id
        for profile_id, _count in sorted(
            profile_counts.items(),
            key=lambda item: (-item[1], item[0]),
        )[: max(1, int(top_limit or 0))]
    ]
    if top_profiles:
        lines.append("Top function profiles: %s." % ", ".join(top_profiles))
    if blocker_counts:
        lines.append(
            "Function identity blockers: %s."
            % ", ".join(
                "%s=%d" % (key, blocker_counts[key])
                for key in sorted(blocker_counts)
            )
        )
    return "\n".join(lines)


def format_parameter_type_correction_summary(plan: CleanPlan, detail_limit: int = 3) -> list[str]:
    corrections = list(plan.type_corrections)
    if not corrections:
        return []
    applied = [item for item in corrections if item.apply_to_preview and not item.blockers]
    blocked = [item for item in corrections if item.blockers or not item.apply_to_preview]
    lines = [
        "Parameter type corrections: %d applied, %d blocked." % (len(applied), len(blocked))
    ]
    applied_detail = _correction_detail_line("Applied corrections", applied, detail_limit, include_blockers=False)
    if applied_detail:
        lines.append(applied_detail)
    blocked_detail = _correction_detail_line("Blocked corrections", blocked, detail_limit, include_blockers=True)
    if blocked_detail:
        lines.append(blocked_detail)
    blocker_counts: dict[str, int] = {}
    for item in blocked:
        blockers = item.blockers or (["preview_disabled"] if not item.apply_to_preview else [])
        for blocker in blockers:
            blocker_counts[blocker] = blocker_counts.get(blocker, 0) + 1
    if blocker_counts:
        lines.append(
            "Type correction blockers: %s."
            % ", ".join(
                "%s=%d" % (key, blocker_counts[key])
                for key in sorted(blocker_counts)
            )
        )
    return lines


def _correction_detail_line(
    label: str,
    corrections: list[object],
    limit: int,
    include_blockers: bool,
) -> str:
    selected = sorted(
        corrections,
        key=lambda item: (
            getattr(item, "parameter_index", -1),
            getattr(item, "profile_id", ""),
            getattr(item, "new_name", ""),
        ),
    )
    if not selected:
        return ""
    detail_limit = max(1, int(limit or 0))
    parts: list[str] = []
    for item in selected[:detail_limit]:
        old_name = _ascii_comment_text(str(getattr(item, "old_name", "") or "arg"))
        new_name = _ascii_comment_text(str(getattr(item, "new_name", "") or old_name))
        old_type = _ascii_comment_text(str(getattr(item, "old_type", "") or "unknown"))
        output_type = _ascii_comment_text(
            str(getattr(item, "display_type", "") or getattr(item, "canonical_type", "") or "unknown")
        )
        profile_id = _ascii_comment_text(str(getattr(item, "profile_id", "") or "profile"))
        text = "%s->%s %s->%s [%s]" % (old_name, new_name, old_type, output_type, profile_id)
        if include_blockers:
            blockers = list(getattr(item, "blockers", []) or [])
            if not blockers and not bool(getattr(item, "apply_to_preview", True)):
                blockers = ["preview_disabled"]
            if blockers:
                text += " blockers=%s" % ",".join(_ascii_comment_text(str(blocker)) for blocker in blockers)
        parts.append(text)
    if len(selected) > detail_limit:
        parts.append("+%d more" % (len(selected) - detail_limit))
    return "%s: %s." % (label, "; ".join(parts))


def _ascii_comment_text(text: str) -> str:
    return text.encode("ascii", "backslashreplace").decode("ascii")
